### PR TITLE
Add support for @apollo/client

### LINKED ISSUE #12: @apollo/client compatibility
Hi! I tried apollo-link-debounce on @apollo/client, but the packages have slightly changed. In particular, `ApolloLink` is now part of `@apollo/client` (rather than `apollo-link`), and a few fields have been added (`onError` and `setOnError`, which seems to be very small functions - probably inheritable?).

### PR DESCRIPTION
**Pull request by 1v4nx**
Fixes #12

### CODE REVIEW

**Comment by 1v4nx** [comment]
@helfer Finally, we got green build! Let me know what you think, and of course feel free to make any extra changes :)

**Comment by 1v4nx** [comment]
Hey @helfer! Any news about this??

**Comment by younes200** [comment]
@helfer could you please merge ?

**Comment by omerman** [comment]
Since no one merged it, if you want to use it right away... -> https://www.npmjs.com/package/omerman-apollo-link-debounce
published it under omerman-apollo-link-debounce.

**Review by lucascicco — APPROVED** [review]

**Comment by helfer** [comment]
Thanks a lot for doing this @1v4nx, and sorry I didn't get around to merging it sooner!

**Comment by helfer** [comment]
Just published 3.0.0 with the changes from this PR 🎉

**Pull request merged**
